"""initial price catalog schema

Revision ID: 392311062b34
Revises: 
Create Date: 2026-08-12 21:11:44.277926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392311062b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_work_type', sa.String(length=100), nullable=False),
    sa.Column('accessory_work_type', sa.String(length=100), nullable=False),
    sa.Column('quantity_per_base_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessory_rules_base_work_type'), 'accessory_rules', ['base_work_type'], unique=False)
    op.create_table('complexity_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_type', 'condition', name='uq_complexity_rule')
    )
    op.create_index(op.f('ix_complexity_rules_work_type'), 'complexity_rules', ['work_type'], unique=False)
    op.create_table('contractor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_overheads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('labor_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pace_units_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_rates_work_type'), 'labor_rates', ['work_type'], unique=True)
    op.create_table('logistics_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('has_elevator', sa.Boolean(), nullable=False),
    sa.Column('surcharge_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_number', 'has_elevator', name='uq_logistics_factor')
    )
    op.create_table('material_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_type', 'material', 'tier', name='uq_material_price')
    )
    op.create_index(op.f('ix_material_prices_work_type'), 'material_prices', ['work_type'], unique=False)
    op.create_table('risk_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precision_level', sa.String(length=20), nullable=False),
    sa.Column('baseline', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('precision_level')
    )
    op.create_table('seasonal_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('wet_process_allowed', sa.Boolean(), nullable=False),
    sa.Column('demand_multiplier', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('waste_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('layout_pattern', sa.String(length=50), nullable=True),
    sa.Column('factor', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_type', 'layout_pattern', name='uq_waste_factor')
    )
    op.create_index(op.f('ix_waste_factors_work_type'), 'waste_factors', ['work_type'], unique=False)
    op.create_table('payment_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('trigger', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warranty_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('work_category', sa.String(length=100), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranty_terms')
    op.drop_table('payment_milestones')
    op.drop_index(op.f('ix_waste_factors_work_type'), table_name='waste_factors')
    op.drop_table('waste_factors')
    op.drop_table('tax_rates')
    op.drop_table('seasonal_factors')
    op.drop_table('risk_baselines')
    op.drop_index(op.f('ix_material_prices_work_type'), table_name='material_prices')
    op.drop_table('material_prices')
    op.drop_table('logistics_factors')
    op.drop_index(op.f('ix_labor_rates_work_type'), table_name='labor_rates')
    op.drop_table('labor_rates')
    op.drop_table('fixed_overheads')
    op.drop_table('contractor_profiles')
    op.drop_index(op.f('ix_complexity_rules_work_type'), table_name='complexity_rules')
    op.drop_table('complexity_rules')
    op.drop_index(op.f('ix_accessory_rules_base_work_type'), table_name='accessory_rules')
    op.drop_table('accessory_rules')
    # ### end Alembic commands ###
